services:
  spark:
    image: docker.io/bitnami/spark:3.5.2
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    ports:
      - '8080:8080'
      - '7077:7077'
    volumes:
      - .:/main/workspace:rw
      - cifs-volume:/main/data:rw
  spark-worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    user: root
    deploy:
      replicas: ${N_REPLICAS}
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=$SPARK_MASTER_URL
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_WORKER_MEMORY=5g
      - SPARK_EXECUTOR_MEMORY=5G
      - SPARK_WORKER_CORES=4
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_USER=spark
    volumes:
      - .:/main/workspace:rw
      - cifs-volume:/main/data:rw
  almond:
    image: almondsh/almond:latest
    ports:
      - 8888:8888
    environment:
      - JUPYTER_TOKEN=almond
    volumes:
      - .:/main/workspace:rw
      - cifs-volume:/main/data:rw
volumes: 
  cifs-volume:
    driver_opts:
      type: cifs 
      o: username=${SMB_USER},password=${SMB_PASSWORD},uid=1021,gid=100,vers=3.0
      device: ${SMB_URL}