services:
  almond:
    build:
      context: .
      dockerfile: almond.Dockerfile
    user: root
    ports:
      - 8002:8888
    environment:
      - JUPYTER_TOKEN=almond
      - JUPYTERLAB_WORKSPACES_DIR=/main
    volumes:
      - .:/main/workspace
      - samba-volume:/main/external
    security_opt:
      - label:disable
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - ALL
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart:
      always
volumes:
  samba-volume:
    driver_opts:
      type: cifs
      o: username=${SMB_USER},password=${SMB_PASSWORD},vers=3.0,rw,file_mode=0777,dir_mode=0777
      device: ${SMB_URL}
